- name: Setup Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true

- name: Enable Redis Repo 6.2
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Install Redis Repo
  ansible.builtin.dnf:
    name: redis
    state: installed

#- name: update Redis Listen Address - /etc/redis.conf
#  ansible.builtin.replace:
#    path: /etc/redis.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'
#
#- name: update Redis Listen Address - /etc/redis/redis.conf
#  ansible.builtin.replace:
#    path: /etc/redis/redis.conf
#    regexp: '127.0.0.1'
#    replace: '0.0.0.0'

- name: update Redis Listen address - /etc/redis.conf & /etc/redis/redis.conf
  ansible.builtin.replace:
    path: {{item}}
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Enable & Restart Services
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

