- name: Load NodeJS module
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load mongo_schema_setup module
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup

- name: Load Prometheus Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter