- name: CopyLogStash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Logstash Restart
  ansible.builtin.systemd:
    name: logstash
    state: restarted


