- name: Disable MYSQL Module
  ansible.builtin.shell: yum module disable mysql -y

- name: Create Mysql Repo
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installation MySQL
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Restart the mysql
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set Root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
