- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove Old Code
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes








#    echo -e "${colour} Download App Code ${nocolour}"
#    curl -o /tmp/$catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/$catalogue.zip &>>${log_file}
#
#    stat_check $?
#
#    echo -e "${colour} Extract the App Code ${nocolour}"
#    cd ${app_path}
#    unzip /tmp/${component}.zip &>>${log_file}
#
#    stat_check $?

