#echo -e "${colour}  Install Maven ${nocolour}"
#yum install maven -y  &>>${log_file}
#
#stat_check $?
#
#app_presetup
#
#echo -e "${colour} Build the code and target  ${nocolour}"
#cd ${app_path}
#mvn clean package &>>${log_file}
#mv target/${component}-1.0.jar ${component}.jar &>>${log_file}
#
#stat_check $?
#
#echo -e "${colour} Copy ${component} service  ${nocolour}"
#  ##copy ${component} service
#cp /home/centos/roboshop_shell/${component}.service /etc/systemd/system/${component}.service
#
#stat_check $?
#
#echo -e "${colour} Install MYSQL  ${nocolour}"
#yum install mysql -y  &>>${log_file}
#
#stat_check $?
#
#echo -e "${colour}  Load Mysql schema ${nocolour}"
#mysql -h mysql-dev.veerankitek.com -uroot -pRoboShop@1 < ${app_path}/schema/${component}.sql  &>>${log_file}
#
#stat_check $?
#
#echo -e "${colour} Restart ${component} services again  ${nocolour}"
#systemctl daemon-reload &>>${log_file}
#systemctl enable ${component} &>>${log_file}
#systemctl restart ${component}  &>>${log_file}
#
#stat_check $?