- name: Setup NodeJS Repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Prerequisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

  #systemd_setup
- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml